// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9d3V0XTiENE4pNeBS-yP5BhU3kT8Jr2U',
    appId: '1:276303135530:web:e6ce1dfd570a31f4b3d453',
    messagingSenderId: '276303135530',
    projectId: 'hackernews-49977',
    authDomain: 'hackernews-49977.firebaseapp.com',
    storageBucket: 'hackernews-49977.appspot.com',
    measurementId: 'G-ZB6C43BH4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFJEICxwBHmDK0UwpvSVt4-4MgzQAIhM0',
    appId: '1:276303135530:android:79058393583f492fb3d453',
    messagingSenderId: '276303135530',
    projectId: 'hackernews-49977',
    storageBucket: 'hackernews-49977.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYRNRnCYDXrEAyqjXYvV_U-05ASJyzNN4',
    appId: '1:276303135530:ios:6f007194be127a59b3d453',
    messagingSenderId: '276303135530',
    projectId: 'hackernews-49977',
    storageBucket: 'hackernews-49977.appspot.com',
    iosClientId: '276303135530-kok0hopirsuqm00elobk3dlpduuhkpbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.hnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYRNRnCYDXrEAyqjXYvV_U-05ASJyzNN4',
    appId: '1:276303135530:ios:205ac81b4b88a3bab3d453',
    messagingSenderId: '276303135530',
    projectId: 'hackernews-49977',
    storageBucket: 'hackernews-49977.appspot.com',
    iosClientId: '276303135530-gv2pgt9bjtdo26ep3q9935ofm2b5pgq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.hnApp.RunnerTests',
  );
}
